#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Robot"
  https://create.arduino.cc/cloud/things/55a6f25e-69a5-4ef7-92a7-09d00eeed538 

  Arduino IoT Cloud Properties description

  The following variables are automatically generated and updated when changes are made to the Thing properties

  bool button;

  Properties which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

// Functions to control motor direction
void forward(){
  //Forward
  //Motor A
  digitalWrite(6, HIGH);
  digitalWrite(5, LOW);
  //Motor B
  digitalWrite(8, LOW);
  digitalWrite(7, HIGH);
}
void reverse(){
  //Reverse
  //Motor A
  digitalWrite(6, LOW);
  digitalWrite(5, HIGH);
  //Motor B
  digitalWrite(8, HIGH);
  digitalWrite(7, LOW);
}
void left(){
  //Spin Left
  //Motor A forwards
  digitalWrite(6, LOW);
  digitalWrite(5, HIGH);
  //Motor B backwards
  digitalWrite(8, LOW);
  digitalWrite(7, HIGH);    
}
void right(){
  //Spin Right
  //Motor A backwards
  digitalWrite(6, HIGH);
  digitalWrite(5, LOW);
  //Motor B forwards
  digitalWrite(8, HIGH);
  digitalWrite(7, LOW);
}
void stop(){
  //All motors off
  //Motor A stop
  digitalWrite(6, LOW);
  digitalWrite(5, LOW);
  //Motor B stop
  digitalWrite(8, LOW);
  digitalWrite(7, LOW);  
}

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  pinMode(8, OUTPUT);
  pinMode(7, OUTPUT);
  pinMode(6, OUTPUT);
  pinMode(5, OUTPUT);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}


void onButtonChange() {
  // Do something
      Serial.print("The robot is... ");
    if (button) {
        Serial.println("DANCING!");
        forward();
        delay(3000);
        reverse();
        delay(3000);
        left();
        delay(3000);
        right();
        delay(3000);
        stop();
    } else {
        Serial.println("RESTING");
    }
}



